movies/urls.py
from django.urls import path, include
from .views import MoviesList, MovieDetail


app_name = 'movies'

urlpatterns = [
    path('', MoviesList.as_view(), name='list'),
    path('<int:pk>', MovieDetail.as_view(), name='detail'),
]

omni_coding_task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

MPAA_Ratings_CHOICES = [
    ('G', 'G'),
    ('PG', 'PG'),
    ('PG13', 'PG13'),
    ('R', 'R'),
    ('NC-17', 'NC-17'),
    ('NC16', 'NC16'),
    ('M18', 'M18'),
    ('R21', 'R21'),
    ('M', 'M'),
    ('M18', 'M18')
]
class Genre(models.Model):
    """Model Definition for Genre"""

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class MPAA_Rating(models.Model):
    """Model Definition for MPAA_Rating"""

    type = models.CharField(choices=MPAA_Ratings_CHOICES, max_length=5)
    label = models.TextField()

    def __str__(self):
        return f'{self.type} - {self.label}'

class Movie(models.Model):
    """Model definition for Movie."""

    name        = models.CharField(max_length=50, blank=False)
    description = models.TextField(blank=False)
    image       = models.ImageField(upload_to='images')
    duration    = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    genres      = models.ManyToManyField(Genre)
    language    = models.CharField(max_length=50)
    mpaa_rating = models.ForeignKey(MPAA_Rating, on_delete=models.CASCADE)
    user_rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    class Meta:
        """Meta definition for Movie."""

        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'

    def __str__(self):
        """Unicode representation of Movie."""
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('movies:detail', kwargs={'pk': self.pk})

    def get_genres_string(self):
        l = [] 
        for _ in self.genres.all():
            l.append(_.name)
        return ', '.join(l)
    get_genres_string.short_description = 'Genre'
    get_genres_string.admin_order_field = 'genres'

movies/views.py
from django.views.generic import ListView, DetailView
from .models import Movie

class MoviesList(ListView):
    template_name = 'movies/home.html'
    context_object_name = 'movies'
    model = Movie

class MovieDetail(DetailView):
    template_name = 'movies/detail.html'
    context_object_name = 'movie'
    model = Movie

movies/templates/movies/detail.html
{% extends 'movies/partials/base.html' %}
{% load static %}


{% block title %} {{ movie.name }} {% endblock title %}
    

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'movies/css/detail.css' %}">
{% endblock extra_head %}


{% block content %}
<main>
    <h1>Movie Listings @ GV Cinema</h1>
    <a href="{% url 'movies:list' %}">Back</a>
    <h2>{{ movie.name }}</h2>
    <p>({{ movie.mpaa_rating.type }}: {{ movie.mpaa_rating.label }})</p>

    <hr>

    <div id="movie-detail">
      <img src="{{ movie.image.url }}">
      <div class="movie-info">
        <h2>Details</h2>
        <p>Genre: {{ movie.get_genres_string }}</p>
        <p>Language: {{ movie.language}}</p>
        <p>Duration: {{ movie.duration }} Minutes</p>
        <p>User Rating: {{ movie.user_rating }}</p>

        <h2>Synopsis</h2>
        <p>{{ movie.description }}</p>
      </div>
    </div>
  </main>
{% endblock content %}

movies/templates/movies/home.html
{% extends 'movies/partials/base.html' %}
{% load static %}


{% block extra_head %}
<link rel="stylesheet" href="{% static 'movies/css/home.css' %}">
{% endblock extra_head %}



{% block content %}
<main>
    <h1>Movie Listings @ GV Cinema</h1>

    <input type="text" placeholder="search movies..." id="movie-filter" onkeyup="myFunction()">
    <hr>

    <h2>Popular Movies this month</h2>
    <div class="movies" id="movies-container">
        {% for movie in movies %}
        <div class="movie-card">
            <img src="{{ movie.image.url }}">

            <h3 class="movie-title"><a href="{{ movie.get_absolute_url }}">{{ movie.name}}</a></h3>
            <p>{{ movie.duration }} min</p>
            <p>User Rating: {{ movie.user_rating }}</p>
        </div>
        {% empty %}
        <h2>No Movies Found</h2>
        <p>Either run this command <br /><code>>python manage.py loadjsontodb</code> </br>or <a
                href="{% url 'admin:movies_movie_add' %}" style="text-decoration:underline; color: blue">add new
                movies</a></p>
        {% endfor %}

    </div>
</main>

<script>
    function myFunction() {
        var input, filter, cards, cardContainer, h5, title, i;
        input = document.getElementById("movie-filter");
        filter = input.value.toUpperCase();
        cardContainer = document.getElementById("movies-container");
        cards = cardContainer.getElementsByClassName("movie-card");
        for (i = 0; i < cards.length; i++) {
            title = cards[i].querySelector("h3.movie-title");
            if (title.innerText.toUpperCase().indexOf(filter) > -1) {
                cards[i].style.display = "flex";
            } else {
                cards[i].style.display = "none";
            }
        }
    }
</script>
{% endblock content %}

movies/templates/movies/partials/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Omni App Task{% endblock %}</title>

    {% block extra_head %}

    {% endblock extra_head %}

</head>

<body>

    {% block content %}

    {% endblock content %}

</body>

</html>